development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: youthtree_development
  username: youthtree
  password:

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: youthtree_test
  username: youthtree
  password:

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: yt_production
  username: yt_production
  password: something

staging:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: yt_staging
  username: yt_staging
  password: something